FROM ghcr.io/open-webui/pipelines:main

RUN pip install --no-cache-dir \
    langchain-openai==1.3.0 \
    langgraph==1.2.4 \
    chromadb==1.5.9 \
    sentence-transformers==5.5.1 \
    python-dotenv \
    neo4j

ENV HF_HOME=/root/.cache/huggingface
